### ISSUE TITLE
Can I use this with Cloudflare Workers?

### ISSUE THREAD

**Issue by slim16165** [google/node-h2-auto-push#39]

**Comment by ofrobots** [comment]
Hi @slim16165 . I do not think you will be able to use this on CloudFlare Workers. Workers do not provide Node.js APIs – they only provide a limited set of web APIs. For example, the `http2` module is not available on Workers. This library is designed for Node.js at the moment.

I'm going to close this issue as it is answered. If this is not correct, feel free to leave a comment.
