### ISSUE TITLE
Push fails when using javascript modules

### ISSUE THREAD

**Issue by douglascvas** [google/node-h2-auto-push#46]
**Version**: v0.4.0
**Browser**: Chrome

**Problem**: 
When importing resources using javascript modules Chrome fails to receive and parse the server pushed resources because there is no `content-type` header for them.

```html
<script type="module" src="myJsFile.js"></script>
```

Message:
```Failed to load module script: The server responded with a non-JavaScript MIME type of "". Strict MIME type checking is enforced for module scripts per HTML spec.```

**Comment by douglascvas** [comment]
Hey @ofrobots thank you for merging the PR. Would you mind releasing/publishing it so we can update the version in `node-fastify-auto-push` to have this issue fixed and closed?

**Comment by ofrobots** [comment]
@douglascvas FYI, there are some [issues](https://mobile.twitter.com/ofrobots/status/1109141970146885632) getting this published that I am working with npm support to get resolved. Stay tuned.
