### ISSUE TITLE
do not store the pushList

### ISSUE THREAD

**Issue by mcollina** [google/node-h2-auto-push#5]
Going through the code, I've seen that the pushList is stored as part of the AutoPush object: https://github.com/google/node-h2-auto-push/blob/master/ts/src/index.ts#L68.

I think it should be a local variable instead.

**Comment by jinwoo** [comment]
@mcollina, yeah I 100% agree with you. Created #6 to address this. Please take a look. Thanks!

**Comment by jinwoo** [comment]
Fixed by #6.
